# Generated by Django 5.2 on 2025-04-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='drawing_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
